version : '3.8'
services:
 app: 
  build: .
  volumes :
   - .:/gym_app
  ports: 
   - "8001:8000"
  image: app:django
  container_name : gym-fitness_app_3
  command: python manage.py runserver 0.0.0.0:8000
  
  
  
  
