# Generated by Django 4.2.4 on 2024-06-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_userdata_remove_water_consumtion_user_delete_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
