# Generated by Django 4.2.4 on 2024-07-03 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=10000)),
                ('indigrients', models.EmailField(max_length=10000)),
                ('food_calorie', models.FloatField(default=0)),
                ('food_carbs', models.FloatField(default=0)),
                ('food_proteins', models.FloatField(default=0)),
                ('food_fats', models.FloatField(default=0)),
                ('meal_type', models.CharField(max_length=100)),
            ],
        ),
    ]
