# Generated by Django 4.2.4 on 2024-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_userdata_calorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='height',
        ),
        migrations.AddField(
            model_name='userdata',
            name='feet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='inches',
            field=models.FloatField(default=0),
        ),
    ]
